In [1]:
import pickle

filename = 'sample.pickle'

loaded_model = pickle.load(open(filename,'rb'))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 0: ordinal not in range(128)

In [2]:
with open("sample.pickle", 'rb') as f:
    loaded = pickle.load(f, encoding="bytes") 

In [22]:

import sys

import numpy as np

if sys.version_info.major == 2:
    X,y,Xtest,ytest = pickle.load(open('sample.pickle','rb'))
else:
    X,y,Xtest,ytest = pickle.load(open('sample.pickle','rb'),encoding = 'latin1')

In [23]:
np.amax(y)

5.0

In [25]:
len(np.unique(y))

5

In [26]:
 y = np.concatenate((y,y),axis=1)

In [27]:
y

array([[1., 1.],
       [3., 3.],
       [4., 4.],
       [1., 1.],
       [3., 3.],
       [4., 4.],
       [4., 4.],
       [4., 4.],
       [1., 1.],
       [2., 2.],
       [4., 4.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [3., 3.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [5., 5.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [1., 1.],
       [1., 1.],
       [5., 5.],
       [4., 4.],
       [2., 2.],
       [5., 5.],
       [1., 1.],
       [5., 5.],
       [5., 5.],
       [3., 3.],
       [5., 5.],
       [2., 2.],
       [3., 3.],
       [1., 1.],
       [2., 2.],
       [5., 5.],
       [4., 4.],
       [4., 4.],
       [5., 5.],
       [5., 5.],
       [2., 2.],
       [2., 2.],
       [4., 4.],
       [5., 5.],
       [2., 2.],
       [4., 4.],
       [3., 3.],
       [1., 1.],
       [5., 5.],
       [1., 1.],
       [5., 5.

In [71]:
import sys

import numpy as np

if sys.version_info.major == 2:
    X,y,Xtest,ytest = pickle.load(open('sample.pickle','rb'))
else:
    X,y,Xtest,ytest = pickle.load(open('sample.pickle','rb'),encoding = 'latin1')





def splitArray(X,y):
    # Inputs
    # X - a N x d matrix with each row corresponding to a training example
    # y - a N x 1 column vector indicating the labels for each training example
    # Outputs
    # X_list - A list of 5 d x k matrices contaiing training values split by the associated y value
    # min_class - minimum class valule -- assumed integer
    # max_class - maximum class value -- assumed integer
    
    samples, features = np.shape(X)
    max_class = int(np.amax(y))
    min_class = int(np.amin(y))
    y = np.concatenate((y,y),axis=1)
    X_list = [[],[],[],[],[]]
    for classification in range(0, max_class-min_class+1):
        X_list[classification] = ( X[ np.where(y == classification + min_class)] ).reshape((-1, features))
    
    return X_list, min_class, max_class

In [72]:
def ldaLearn(X,y):
    # Inputs
    # X - a N x d matrix with each row corresponding to a training example
    # y - a N x 1 column vector indicating the labels for each training example
    #
    # Outputs
    # means - A d x k matrix containing learnt means for each of the k classes
    # covmat - A single d x d learnt covariance matrix 
    
    # IMPLEMENT THIS METHOD 
    X_split, min_class, max_class = splitArray(X,y)
    
    means =  [[],[],[],[],[]]
    for classification in range(max_class-min_class+1):
        means[classification] = np.mean(X_split[classification],axis=0)
    covmat = np.cov(X.T,bias=1)
    return means,covmat

In [73]:
ldaLearn(X,y)

([array([2.84353732, 3.22948323]),
  array([6.06321127, 8.19216551]),
  array([ 4.22278151, 11.96673625]),
  array([11.00791698,  4.70430105]),
  array([ 9.72829148, 11.82494404])],
 array([[10.78687726,  1.21886861],
        [ 1.21886861, 14.227347  ]]))

In [35]:
### LDA

import numpy as np
from scipy.optimize import minimize
from scipy.io import loadmat
from numpy.linalg import det, inv
from math import sqrt, pi
import scipy.io
import matplotlib.pyplot as plt
import pickle
import sys

def ldaLearn(X,y):
    # Inputs
    # X - a N x d matrix with each row corresponding to a training example
    # y - a N x 1 column vector indicating the labels for each training example
    #
    # Outputs
    # means - A d x k matrix containing learnt means for each of the k classes
    # covmat - A single d x d learnt covariance matrix 
    
    # IMPLEMENT THIS METHOD 
    
    diff_classes = len(np.unique(y))
    
    total_data = np.concatenate((X,y),axis=0)
    
    
    return means,covmat


In [54]:
total_data = np.concatenate((X,y),axis=1)

In [64]:
diff_classes = np.unique(y)

In [70]:
means = {}
for i in diff_classes:
    tmp = total_data[np.where(total_data[:,2]==i)]
    means[i]=(np.mean(tmp[:,0]),np.mean(tmp[:,1]))

In [67]:
means

{1.0: (2.8435373216209836, 3.229483232900744),
 2.0: (6.063211269618671, 8.192165511028163),
 3.0: (4.222781513869941, 11.966736254481463),
 4.0: (11.007916982412592, 4.7043010454682195),
 5.0: (9.728291481754447, 11.824944042387495)}